### ISSUE TITLE
How to install bff packages and nim resources on clients

### ISSUE THREAD

**Issue by AntonioBassoJR** [IBM/ansible-power-aix#343] opened 2023-10-02 11:28 UTC
**Is your feature request related to a problem? Please describe.**
I'm not able to use installp to install .bff packages or allocate/request a package on a nim client.

**Describe the solution you'd like**
Use installp to manage packages on the nim client side and also use .bff packages for installation.

**Describe alternatives you've considered**
I've been using shell to allocate and install it.

**Additional context**

**Comment by nitismis** [comment] 2023-10-06 05:09
Hi @AntonioBassoJR 
****You can use the nim module to update and allocate packages.** Currently only update is supported on nim client using nim module.** Support for new installs on the client is in our pipeline and we are planning to include this support in our next year release. Also for any nim related feature you can go through our nim_* modules. Let us know if you are looking for any new feature or enhancements in our existing modules.

Thanks

**Comment by nitismis** [comment] 2023-10-12 03:03
We have prioritized this item for early 2024. This item is duplicate of issue #82. We will track this through #82.

**Closed as completed by nitismis** 2023-10-12 03:03 UTC
