### ISSUE TITLE
"Request failed: <urlopen error unknown url type: https>"

### ISSUE THREAD

**Issue by mrajesh1** [IBM/ansible-power-aix#84] opened 2021-04-22 18:50 UTC
**Describe the bug**

**To Reproduce**
5. fatal: [servername.domain.com]: FAILED! => {"changed": false, "dest": "/var/opt/ansible/GTS/tools/ConfigMergeTool.jar", "elapsed":, 0, "msg": "Request failed: <urlopen error unknown url type: https>", "url": "https://XX.XX.XX.XX:8081/repository/GCM/tools/ConfigMergeTool.jar"}

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. AIX 7.2.4.0]
 - Python Version: [e.g. 2.7.5, 3.6]
 - OpenSSH Version: [e.g. 1.0.2]
 - Ansible Version: [e.g. 2.10.7]
 - AIX Collection Version: [e.g. 1.2.1]

**Additional context**

**Comment by mrajesh1** [comment] 2021-04-22 18:51
we are getting the below error while executing playbook, we are using AIX OS.

fatal: [servername.domain.com]: FAILED! => {"changed": false, "dest": "/var/opt/ansible/GTS/tools/ConfigMergeTool.jar", "elapsed":, 0, "msg": "Request failed: <urlopen error unknown url type: https>", "url": "https://XX.XX.XX.XX:8081/repository/GCM/tools/ConfigMergeTool.jar"}

**Comment by nitismis** [comment] 2021-05-13 15:08
Hi Rajesh !
The issue is not understandable from the description you have provided.
We need module from where this issue is coming.
Please provide the playbook (yml file) and command you have used. It will help us in recreating the issue.

Thanks

**Comment by nitismis** [comment] 2021-05-13 15:22
I am closing the issue for now. Please reopen the issue once you have more details.

**Closed as completed by nitismis** 2021-05-13 15:22 UTC
