### ISSUE TITLE
alt_disk_copy - Support for mirrored rootvg

### ISSUE THREAD

**Issue by neikei** [IBM/ansible-power-aix#354] opened 2023-10-11 05:26 UTC
**Describe the bug**
As described in issue https://github.com/IBM/ansible-power-aix/issues/278 we had some issues with the alt_disk.py.
Maybe the title was a bit misleading, because the main issue is that mirrored rootvgs are not supported with "disk_size_policy " right now.

**To Reproduce**
1. Check the size of your rootvg
2. Get 3 disks with the same size
3. Create mirror of rootvg ```mirrorvg rootvg <new_hdisk>```
4. Check ```lsvg rootvg``` and ```lsvg -l rootvg``` which should show 2 PPs for each LP
5. Try to run the alt_disk_copy Playbook
6. Now we have 2 unused None-disks to develop a alt_disk_copy solution for mirrored rootvgs

**Expected behavior**

```bash
# The current alt_disk.py ignores the rootvg mirror and uses one single hdisk
alt_disk_copy -d hdisk9 -B

# To create a useable altinst_rootvg with mirrored disks we have to use 2 None-disks
alt_disk_copy -d "hdisk4 hdisk14" -B

# The result of the alt_disk_copy will show 2 rootvg disks and 2 alt_rootvg disks
$ lspv | grep rootvg
hdisk4          xxxxxxxxxx182706           altinst_rootvg          # DISK_SIZE: 61440
hdisk5          xxxxxxxxxx35c55d           rootvg          active  # DISK_SIZE: 61440
hdisk14         xxxxxxxxxx1827d9           altinst_rootvg          # DISK_SIZE: 61440
hdisk15         xxxxxxxxxx35c763           rootvg          active  # DISK_SIZE: 61440
```

**Environment (please complete the following information):**
 - OS: 7200-05-03-2148
 - Python Version: 3.9.16
 - Ansible Version: 2.14.2
 - AIX Collection Version: 1.6.1

**Comment by neikei** [comment] 2023-10-11 05:55
Workaround is available, but unfortunately not really documented. We found this alternate while reviewing the code and were able to clone on two hdisks.

```yaml
  - name: Perform an alternate disk copy of the rootvg to a list of hdisks
    ibm.power_aix.alt_disk:
      action: copy
      targets:
        - hdisk4
        - hdisk14
```

**Comment by nitismis** [comment] 2023-10-12 02:59
@neikei,
We are done with the Q3 items but you can expect us to work on this in Q4 and we will make this enhancement available by this year end.
Thanks

**Comment by carstenstephan** [comment] 2024-01-15 05:05
Any news on this request?

**Comment by Architecttheday** [comment] 2024-01-16 13:35
Hi,
my hope was to see this in the Q1 release. But it seams not to be in.
Is it planned for the next release?
Thanks

**Comment by schamola** [comment] 2024-01-19 17:07
Hi @neikei , 
We are working on the issue, the fix will be available soon. We just have few queries....

As per our understanding, the issue is that when using alt_disk_copy on a mirrored rootvg, bigger space is being considered ( As in, in the above mentioned case: the complete size of hdisk5 and hdisk15 is being taken into consideration and according to that, the disk is being chosen), right ?

One more thing, In the expected behaviour section, you have mentioned this command: 'alt_disk_copy -d "hdisk4 hdisk14" -B'. 
Here, why are we using 2 disks as targets for alt_disk_copy (thus, creating in total 4 copies of the same data) ? Is there any particular requirement that we may are missing upon ?

**Comment by schamola** [comment] 2024-01-26 07:01
Hi @neikei @carstenstephan @Architecttheday !

We have opened a PR for the requested changes (PR number: #409), can you please check if the changes are working fine on your environment ?
After your approval, we will merge the code to our main repo.

Thanks !

**Comment by nitismis** [comment] 2024-01-31 06:59
PR is merged now.

**Closed as completed by nitismis** 2024-01-31 06:59 UTC
Labels: enhancement
