### ISSUE TITLE
Module "nim_resource" is not providing expected outcome.

### ISSUE THREAD

**Issue by snehald12** [IBM/ansible-power-aix#373] opened 2023-11-15 19:37 UTC
When trying to use ibm.power_aix.nim_resource module to generate a list of machine groups configured on the NIM server, the stdout dictionary and module generated "nim_resources" dictionary differ.  It seems the "nim_resources" dictionary has a bug.

The issue is related to the IBM AIX collection where machine group in stdout lines of the job output shows different that the manual command  "lsnim -l -t mac_group" run output.

EVERY group dictionary the module has constructed has the SAME members list, even though on the NIM server they are different.

Module's constructed "nim_resources" dictionary:

    "UC_XXX_TEST1": {
                "class": "groups",
                "member1": "xxxxx11",
                "member4": "xxxxx12",
                "member5": "xxxxx13",
                "type": "mac_group"
  },
            "UC_XXX_TEST2": {
                "class": "groups",
                "member1": "xxxxx11",
                "member4": "xxxxx12",
                "member5": "xxxxx13",
                "type": "mac_group"
            },
            
Module's "stdout_lines":

        "stdout_lines": [
            "UC_XXX_TEST1:",
            "   class    = groups",
            "   type     = mac_group",
            "   comments = first mac group for UC XXX",
            "   member1  = xxxxx50u",
            "   member2  = xxxxx51u",
            "   member4  = xxxxx67u",
            
Manually running the command on AIX node "/usr/sbin/lsnim -l -t mac_group" gives the correct results as shown in modules stdout lines above.

**To Reproduce**
NA

**Expected behavior**
The stdout dictionary and module generated "nim_resources" dictionary  shout be same.

**Environment (please complete the following information):**
 - AIX OS: 7200-05-06-2320
 - Python Version: 3.9.13
 - Ansible Version: core 2.13.3
 - AIX Collection Version: ibm.power_aix 1.7.2

Playbook Used:
~~~
---
- hosts: localhost
  gather_facts: false
  vars_files: 
    - ../vars.yml

  tasks:
    - name: Gather NIM machine group names
      ibm.power_aix.nim_resource:
        action: show
        object_type: mac_group
      register: nim_mac_group
      check_mode: false

    - name: DEBUG nim resources
      ansible.builtin.debug:
        var: nim_mac_group

    - meta: end_play
    - ~~~`

Customer suspects if the module has been fully developed or not as they noticed  "mac_group" is not listed either section of the list:
https://github.com/IBM/ansible-power-aix/blob/73142877d67e349e41fba715657a8e857f88728e/plugins/modules/nim_resource.py#L208


Thanks.

**Comment by schamola** [comment] 2023-11-16 05:35
Hi @snehald12 ,
Thanks for reporting this issue, we will look into it.

**Comment by schamola** [comment] 2023-11-27 06:31
Hi @snehald12 , 
We have figured out the root cause, and will push the code changes after testing them out.

**Comment by nitismis** [comment] 2023-11-29 09:41
Fix is merged. Closing the issue.

**Closed as completed by nitismis** 2023-11-29 09:41 UTC
Labels: bug
