### ISSUE TITLE
AIX OS update fails "Cannot get oslevel from lpp source name: 7100-05-09_lpp_resource"

### ISSUE THREAD

**Issue by vijanaim** [IBM/ansible-power-aix#263] opened 2023-02-02 13:47 UTC
The issue after we issuing nim update is this something have to do at module level 
"changed": false,
    "invocation": {
        "module_args": {
            "action": "update",
            "asynchronous": false,
            "boot_client": true,
            "device": null,
            "force": false,
            "group": null,
            "location": null,
            "lpp_source": "7100-05-09_lpp_resource",
            "object_type": "all",
            "resource": null,
            "script": null,
            "targets": [
                "Test_ansible"
            ]
        }
    },
    "meta": {
        "Test_ansible": {
            "messages": [
                "Cannot get oslevel from lpp source name: 7100-05-09_lpp_resource"
            ]
        },
        "messages": []
    },
    "msg": "NIM update operation successful. See status and meta for details.",
    "nim_node": {

Here is the playbook info.

- name: AIX Patching Playbook 
  hosts: XXXXXX
  vars: 

    nim_master: NIMMASTER
  collections:
    - ibm.power_aix
  tasks:

  - name: Cleanup if any existing alt_disk_copy backup existing 
    alt_disk:
      action: clean

  - name: Create an new alt_disk_copy for backup
    alt_disk:
      targets: hdisk0

  - name: Run AIX Update
    nim:
      action: update
      lpp_source: 7100-05-09_lpp_resource
      targets: Test_ansible
    delegate_to: "{{ nim_master }}"

**Comment by nitismis** [comment] 2023-02-09 08:42
We are looking into the issue. Will update here.

**Comment by Vijaybabuanaimuthu** [comment] 2023-02-16 11:30
Hi Nitish, 
Further to our discussion, please find the details and looking forward hear from you. 

[root@PRDANSAUTAPP01 IBL]# cat Step_03_IndusInd_aix_patching.yml
---

- name: AIX Patching Playbook
  hosts: P8_NIM71 ####### The partitions which you want to patch
  collections:
    - ibm.power_aix
  tasks:
    - name: Run AIX Update
      nim:
        action: 'update'
        asynchronous: true
        force: 'false'
        targets: Test_ansible
        lpp_source: 7100-05-09_lpp_resource
[root@PRDANSAUTAPP01 IBL]#


changed: [P8_NIM71] => {
    "changed": true,
    "cmd": "nim -o cust -a lpp_source=7100-05-09_lpp_resource -a fixes=update_all -a accept_licenses=yes -a async=yes Test_ansible",
    "invocation": {
        "module_args": {
            "action": "update",
            "asynchronous": true,
            "boot_client": true,
            "device": null,
            "force": false,
            "group": null,
            "location": null,
            "lpp_source": "7100-05-09_lpp_resource",
            "object_type": "all",
            "resource": null,
            "script": null,
            "targets": [
                "Test_ansible"
            ]
        }
    },
    "meta": {
        "messages": [
            "Asynchronous software customization for client(s) Test_ansible with resource 7100-05-09_lpp_resource.",
            "Successfully updated installed software."
        ]
    },
    "msg": "NIM update operation successful. See status and meta for details.",
    "nim_node": {
        "lpp_source": {
            "7100-05-09_lpp_resource": "/export/nim/lpp_source/7100-05-09_lpp_resource",
            "7100-05-10_lpp_resource": "/export/nim/lpp_source/7100-05-10_lpp_resource",
            "730lpp_res": "/export/nim/lpp_source/730lpp_res",
            "aix7159_lpp_source": "/export/nim/lpp_source/SP9",
            "new_lpp_source": "/export/nim_lpp_source"
        },
        "master": {
            "Cstate": "ready for a NIM operation",
            "type": "master"
        },
        "standalone": {
            "P8_NIM71": {
                "Cstate": "ready for a NIM operation",
                "Mstate": "currently running",
                "cable_type1": "tp",
                "class": "machines",
                "connect": "nimsh",
                "if1": "master_net P8_NIM71 0",
                "netboot_kernel": "64",
                "platform": "chrp",
                "prev_state": "ready for a NIM operation",
                "type": "standalone"
            },
            "Test_ansible": {
                "Cstate": "ready for a NIM operation",
                "Cstate_result": "failure",
                "Mstate": "currently running",
                "cable_type1": "N/A",
                "class": "machines",
                "connect": "nimsh",
                "cpuid": "00FBEAF94C00",
                "if1": "ent-Network1 Test_ansible 42B0D4397100 ent0",
                "netboot_kernel": "64",
                "platform": "chrp",
                "prev_state": "customization is being performed",
                "type": "standalone"
            }
        },
        "vios": {}
    },
    "rc": 0,
    "status": {},
    "stderr": "",
    "stderr_lines": [],
    "stdout": "",
    "stdout_lines": [],
    "targets": [
        "Test_ansible"
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************
P8_NIM71                   : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

[root@PRDANSAUTAPP01 IBL]#

**Comment by Vijaybabuanaimuthu** [comment] 2023-02-16 11:33
In the playbook .. 
---

- name: AIX Patching Playbook
  **hosts: P8_NIM71** 
  collections:
    - ibm.power_aix
  tasks:
    - name: Run AIX Update
      nim:
        action: 'update'
        asynchronous: true
        force: 'false'
        targets: Test_ansible
        lpp_source: 7100-05-09_lpp_resource

In hosts if we mention Test_ansible, the playbook failed with lsmin command was not found like that . let me know your suitable time we can discuss further on this.

**Comment by nitismis** [comment] 2023-02-23 06:14
@Vijaybabuanaimuthu @vijanaim 
I think there is some confusion here in the usage of playbook and nim module.
nim module playbooks are supposed to run on nim server. So, in "hosts", you need to provide nim server and in "targets", you need to provide the nim client which you want to update. Now, because Test_ansible is not a nim sever, the module is throwing error and this is the reason why "lsnim" command is failing. Your P8_NIM71 is a nim server, so, when you provide it as a hosts everything is working fine (for this you have posted the result). So, I dont think this is an error. This is how the module is suppose to work. Please go through the documentation here first:
https://github.com/IBM/ansible-power-aix/blob/dev-collection/plugins/modules/nim.py
This is what the documentation says:
targets:
    description:
    - Specifies the NIM clients to perform the action on.
    - C(foo*) specifies all the NIM clients with name starting by 'foo'.
    - C(foo[2:4]) specifies the NIM clients among foo2, foo3 and foo4.
    - C(*) or C(ALL) specifies all the NIM clients.
    - C(vios) or C(standalone) specifies all the NIM clients of this type.

Closing the issue because it is working as per expectation.

**Closed as completed by nitismis** 2023-02-23 06:14 UTC
Labels: bug

**Comment by Rich-J-AIX** [comment] 2023-02-28 16:58
From experience I think the problem is that the module only works if the LPP Source matches the desired format.
7100-05-09_lpp_resource is not in the desired format.

To work as specified in the module the lpp_source names should match:                              
                                  VVVV-TT-SS-YYMM-lpp_source
                             e.g. 7300-01-01-2246-lpp_source

#### from nim.py
```
 # extract oslevel from lpp source
 oslevel_elts = []
 matched = re.match(r"^([0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{4})-lpp_source$", new_lpp_source)
 if matched:
     oslevel_elts = matched.group(1).split('-')
 else:
     msg = 'Cannot get oslevel from lpp source name: {0}'.format(new_lpp_source)
     results['meta'][target]['messages'].append(msg)
     module.log('NIM - WARNING: On {0} '.format(target) + msg)
     continue
```
